#  Maven image for development
FROM maven:3.9.4-eclipse-temurin-21 AS server
WORKDIR /server
COPY ./server .
RUN mvn clean install -DskipTests
CMD ["mvn", "spring-boot:run"]
EXPOSE 8080



FROM node:20-slim AS app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NODE_ENV=development
ENV PNPM_VERSION=9.12.2
 
RUN npm install -g npm@latest && \
    npm install -g corepack@latest && \
    corepack enable
RUN corepack prepare pnpm@${PNPM_VERSION} --activate

COPY ./app /app
WORKDIR /app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm -r --prod=false install --frozen-lockfile
CMD ["pnpm", "run", "dev"]
EXPOSE 3000
