services:
  plutarch_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: app
    container_name: plutarch_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6300:3000"
    expose:
      - "3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - plutarch_server
    networks:
      - plutarch_network

  plutarch_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: server
    container_name: plutarch_server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6200:8080"
    expose:
      - "8080"
    volumes:
      - ./server:/server
      - ~/.m2:/root/.m2
    depends_on:
      - plutarch_database
    networks:
      - plutarch_network

  plutarch_database:
    image: postgres:14.1-alpine
    container_name: plutarch_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "6000:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plutarch_network

  plutarch_database_client:
    image: dpage/pgadmin4:latest
    container_name: plutarch_database_client
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DATABASE_CLIENT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_CLIENT_PASSWORD}
    ports:
      - "6100:80"
    depends_on:
      - plutarch_database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - plutarch_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  plutarch_network:
    driver: bridge
